jobs:
- job: iOS_CI_on_Mac
  pool:
    vmImage: 'macOS-13'
  variables:
    PROTO_CACHE_DIR: $(Pipeline.Workspace)/proto_ccache
    ORT_CACHE_DIR: $(Pipeline.Workspace)/ort_ccache
    TODAY: $[format('{0:dd}{0:MM}{0:yyyy}', pipeline.startTime)]
  timeoutInMinutes: 150
  steps:
    - template: templates/use-xcode-version.yml
    - template: templates/mac-build-step-with-cache.yml
      parameters:
        WithCache: true
        Today: $(TODAY)
        AdditionalKey: onnxruntime
        CacheDir: $(ORT_CACHE_DIR)
        ChangeEveryCommit: true
        BuildStep:
          - script: |
              python3 $(Build.SourcesDirectory)/tools/ci_build/build.py \
                --skip_submodule_sync \
                --build_dir $(Build.BinariesDirectory)/iOS \
                --build_shared \
                --use_coreml \
                --use_xnnpack \
                --ios \
                --ios_sysroot iphonesimulator  \
                --osx_arch x86_64 \
                --apple_deploy_target 12.0 \
                --use_xcode \
                --config RelWithDebInfo \
                --build_apple_framework \
                --parallel
            displayName: (CPU, CoreML, XNNPACK EPs) Build onnxruntime for iOS x86_64 and run tests using simulator
            env:
              CC: clang
              CXX: clang++
              CCACHE_CPP2: 1
              CCACHE_DEPEND: 1
              CCACHE_SLOPPINESS: modules
              CCACHE_DIR: $(ORT_CACHE_DIR)
